#!/bin/bash

# This writes temporary files to $TMPDIR because otherwise the vault
# compilation tools incorrectly detects its source as being under git
# when it detects the vault-rpm parent git.

REQUIRED="git gpg make python3 g++ find"
NODEVERSION=22.5.1
YARNVERSION=1.22.22

. /etc/os-release

if [[ "$VERSION" == 7* ]]; then
    echo "Run this on el8 or el9" >&2
    exit 2
fi

for TOOL in $REQUIRED; do
    if [ ! -x /usr/bin/$TOOL ]; then
	echo "Required command '$TOOL' missing" >&2
	exit 2
    fi
done

BASE=vault-src
set -ex
cd "`dirname $0`"
HERE=$PWD
cd ${TMPDIR:-/tmp}
for OLDBASE in $BASE-*; do
    if [ -d $OLDBASE/go ]; then
	# this is in case it wasn't fully created and chmodded
        PATH=$PWD/$OLDBASE/go/bin:$PATH GOPATH=$PWD/$OLDBASE/gopath go clean -modcache
    fi
done
rm -rf $BASE-*
VERSION="`sed -n 's/^Version:[ \t]*//p' $HERE/vault.spec`"
BASE="$BASE-$VERSION"
mkdir $BASE
cd $BASE

# install required node.js version
curl -sSL https://nodejs.org/download/release/v$NODEVERSION/node-v$NODEVERSION-linux-x64.tar.gz | tar -xzf -
export NODEJS_HOME=$PWD/node-v$NODEVERSION-linux-x64
PATH=$NODEJS_HOME/bin:$PATH
node --version
#npx --yes update-browserslist-db@latest

# install yarn 
YARN_HOME=$PWD/yarn-$YARNVERSION
mkdir $YARN_HOME
OLDHOME=$HOME
HOME=$YARN_HOME
touch $HOME/.profile
curl -o- -sSL https://yarnpkg.com/install.sh | bash -s -- --version $YARNVERSION
. $HOME/.profile
gpgconf --kill gpg-agent
HOME=$OLDHOME
yarn --version

# install vault source
curl -sSL https://codeload.github.com/hashicorp/vault/tar.gz/v$VERSION | tar xzf -

# install required go version
mkdir gopath
export GOPATH=$PWD/gopath
GOVERSION="`cat vault-$VERSION/.go-version`"
curl -sSL https://golang.org/dl/go$GOVERSION.linux-amd64.tar.gz | tar -xzf -
PATH=$PWD/go/bin:$GOPATH/bin:$PATH
go version

cd vault-$VERSION
make bootstrap
make static-dist
make prep
cd ..
cd ..

rm -rf $NODEJS_HOME $YARN_HOME
find $GOPATH/pkg/mod -type d ! -perm -200 -print0|xargs -0 -r chmod u+w
rm -rf $GOPATH/mod/*.*
tar --exclude .git -czf $HERE/$BASE.tar.gz $BASE
rm -rf $BASE
